export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: 'WordUp Demo Site',
      description: 'Beautifully designed Nuxt Content template built with shadcn-vue and unocss.',
      ogImage: '/hero.png',
      ogImageComponent: 'ShadcnDocs',
      ogImageColor: 'dark',
      umami: {
        enable: false,
        src: 'https://cloud.umami.is/script.js',
        dataWebsiteId: '',
      },
    },
    theme: {
      color: 'orange',
      radius: 0.5,
    },
    banner: {
      enable: true,
      showClose: true,
      content: 'Welcome to **shadcn-site-nuxt**',
      to: 'https://github.com/wordup-md/nuxt-layer-shadcn-unocss',
      target: '_blank',
      border: true,
    },
    header: {
      title: 'WordUp Demo Site',
      showTitle: true,
      logo: {
        light: '/logo.svg',
        dark: '/logo-dark.svg',
      },
      border: true,
      darkModeToggle: true,
      nav: [{
        title: 'Docs',
        links: [{
          title: 'Getting Started',
          to: '/getting-started',
          description: 'Start building your document with shadcn-site-nuxt',
          icon: 'lucide:rocket',
        }, {
          title: 'Development',
          to: '/development',
          description: 'Discover the configurations and exposed APIs.',
          target: '_self',
          icon: 'lucide:code',
        }],
      }, {
        title: 'Credits',
        links: [{
          title: 'shadcn-ui',
          to: 'https://ui.shadcn.com/',
          description: 'For the beautiful component design & docs design',
          target: '_blank',
        }, {
          title: 'shadcn-vue',
          to: 'https://www.shadcn-vue.com/',
          description: 'For the vue port of shadcn-ui & some docs component source',
          target: '_blank',
        }, {
          title: 'Docus',
          to: 'https://docus.dev/',
          description: 'For inspiration & some docs component source',
          target: '_blank',
        }, {
          title: 'Nuxt Content',
          to: 'https://content.nuxt.com/',
          description: 'Content made easy for Vue Developers',
          target: '_blank',
        }],
      }, {
        title: 'Use This Template',
        to: '/getting-started/introduction',
        target: '_self',
        showLinkIcon: true,
      }],
      links: [{
        icon: 'lucide:twitter',
        to: 'https://x.com/wordup_md',
        target: '_blank',
      }],
    },
    aside: {
      useLevel: true,
      collapse: false,
      collapseLevel: 1,
      folderStyle: 'default',
    },
    main: {
      // padded: true,
      breadCrumb: {
        showIcon: true,
      },
      showTitle: true,
      codeCopyToast: true,
      editLink: {
        enable: true,
        pattern: 'https://github.com/wordup-md/nuxt-layer-shadcn-unocss/edit/main/.playground/content/:path',
        text: 'Edit this page',
        icon: 'lucide:square-pen',
        placement: ['pageFooter', 'toc'],
      },
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
        'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
        'tailwind.config.js': 'vscode-icons:file-type-tailwind',
        'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
        'vue': 'vscode-icons:file-type-vue',
        'ts': 'vscode-icons:file-type-typescript',
        'tsx': 'vscode-icons:file-type-typescript',
        'mjs': 'vscode-icons:file-type-js',
        'cjs': 'vscode-icons:file-type-js',
        'js': 'vscode-icons:file-type-js',
        'jsx': 'vscode-icons:file-type-js',
        'md': 'vscode-icons:file-type-markdown',
        'mdc': 'vscode-icons:file-type-markdown',
        'py': 'vscode-icons:file-type-python',
        'npm': 'vscode-icons:file-type-npm',
        'pnpm': 'vscode-icons:file-type-pnpm',
        'npx': 'vscode-icons:file-type-npm',
        'yarn': 'vscode-icons:file-type-yarn',
        'bun': 'vscode-icons:file-type-bun',
        'yml': 'vscode-icons:file-type-yaml',
        'json': 'vscode-icons:file-type-json',
        'terminal': 'lucide:terminal',
      },
    },
    footer: {
      credits: 'Made with ❤️ by [Emmanuel Salomon](https://github.com/ManUtopiK/) with :icon{.rotate-x-180.translate-y-1 name="i-pajamas:markdown-mark-solid"} [WordUp.md](https://wordup.md)',
      links: [
        {
          title: 'shadcn-vue',
          alt: 'shadcn vue logo',
          icon: 'https://www.shadcn-vue.com/favicon.ico',
          to: 'https://www.shadcn-vue.com/',
          target: '_blank',
        },
        {
          alt: 'GitHub logo',
          icon: 'lucide:github',
          to: 'https://github.com/wordup-md/nuxt-layer-shadcn-unocss',
          target: '_blank',
        },
      ],
    },
    toc: {
      enable: true,
      title: 'On This Page',
      links: [{
        title: 'Star on GitHub',
        icon: 'lucide:star',
        to: 'https://github.com/wordup-md/nuxt-layer-shadcn-unocss',
        target: '_blank',
        showLinkIcon: true,
      }, {
        title: 'Create Issues',
        icon: 'lucide:circle-dot',
        to: 'https://github.com/wordup-md/nuxt-layer-shadcn-unocss/issues',
        target: '_blank',
        showLinkIcon: true,
      }],
      carbonAds: {
        enable: false,
      },
    },
    search: {
      inAside: false,
    },
  },
})
